export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED"
export const LOAD_MORE_USERS_REQUESTED = "LOAD_MORE_USERS_REQUESTED"
export const LOAD_MORE_USERS_SUCCESS = "LOAD_MORE_USERS_SUCCESS"